const STORIES = [
  { type: 'video', src: 'Screens motion/Screen01.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen02.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen03.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen04.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/screen05.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen06.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen07.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen08.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen09.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen10.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen11.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen12.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen13.mp4', poster: '#FCFAF7' },
  { type: 'stamps' },
  { type: 'video', src: 'Screens motion/Screen16.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen17.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen18.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen19.mp4', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen20.mp4', poster: '#FCFAF7' },
  { type: 'image', src: 'Screens motion/Screen21.png', poster: '#FCFAF7' },
  { type: 'image', src: 'Screens motion/Screen22.png', poster: '#FCFAF7' },
  { type: 'video', src: 'Screens motion/Screen23.mp4', poster: '#FCFAF7' },
];
